### DISCUSSION TITLE
Provide script for health check

### DISCUSSION THREAD

**Discussion by thiagogarbazza** [grafana/docker-otel-lgtm#335] [Show and tell]
health-check.sh example:
```shell
#!/bin/bash

curl --fail http://localhost:3000/api/health || exit 99
curl --fail http://localhost:3100/ready || exit 98
curl --fail http://localhost:9090/api/v1/status/runtimeinfo || exit 97
curl --fail http://localhost:3200/ready || exit 96
```

compose.yaml example:
```yaml
services:
  otel-lgtm:
    image: grafana/otel-lgtm
    volumes:
      - otel-lgtm-data:/data
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    healthcheck:
      test: /opt/health-check.sh
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 1m
      start_interval: 10s

  my-app:
    image: my-app:latest
    # ...
    depends_on:
      otel-lgtm:
        condition: service_healthy

volumes:
  otel-lgtm-data:
```

Will it allow my service to go up after otel-lgtm.

**Comment by zeitlinger** [comment]
I think this equivalent to https://github.com/grafana/docker-otel-lgtm/blob/4beb0956b8c2d31ce7ba6138aaed6ba1b5f70ba8/k8s/lgtm.yaml#L44-L48

Did you try that out?

**Comment by thiagogarbazza** [comment]
It worked perfectly.


Working example:
```yaml
services:
  otel-lgtm:
    image: grafana/otel-lgtm
    volumes:
      - otel-lgtm-data:/data
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    healthcheck:
      test: cat /tmp/ready
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 1m
      start_interval: 10s

  my-app:
    image: my-app:latest
    # ...
    depends_on:
      otel-lgtm:
        condition: service_healthy

volumes:
  otel-lgtm-data:
```
