### DISCUSSION TITLE
Enabling Grafana Image Renderer Plugin

### DISCUSSION THREAD

**Discussion by daviddwlee84** [grafana/docker-otel-lgtm#414] [Q&A] [answered]
I'm new to Grafana today. When I first try the `http://localhost:3000/render/...` API (with [`run-lgtm.sh`](https://github.com/grafana/docker-otel-lgtm/blob/831ca01df00b3456aff252b5790b325b44574761/run-lgtm.sh))

![image](https://github.com/user-attachments/assets/dbe779b0-1071-4bf9-a3ad-465ad8fdda80)

Found that it is not maintained by the Plugin Catalog

![image](https://github.com/user-attachments/assets/4f240de0-dd3c-4f9b-9e86-64fb78b5710f)

According to Grafana Image Renderer, it provide a way of docker compose with pure Grafana image

https://github.com/grafana/grafana-image-renderer?tab=readme-ov-file#run-in-docker

I'm thinking if there is way to keep it simple (without running another image) with `otel-lgtm` image only

I tried `docker exec -it lgtm bash` and `grafana-cli plugins install grafana-image-renderer` will get `bash: grafana-cli: command not found`

And then tried to build with `GF_INSTALL_PLUGINS="grafana-image-renderer"` which was not worked either

```bash
#!/bin/bash

RELEASE=${1:-latest}

docker buildx build -f docker/Dockerfile docker --tag grafana/otel-lgtm:"${RELEASE}" --build-arg "GF_INSTALL_PLUGINS=grafana-image-renderer"
```
https://github.com/grafana/docker-otel-lgtm/blob/831ca01df00b3456aff252b5790b325b44574761/build-lgtm.sh#L5

Does anybody knows the best practice?

---

- https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/
- https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#build-a-grafana-docker-image-with-pre-installed-plugins (`GF_INSTALL_PLUGINS`)

**Comment by zeitlinger** [comment]
you should be able to pass this arg when starting the image - no need to rebuild

**Reply by daviddwlee84** [reply]
I tried these

```bash
...

docker run \
	--name lgtm \
	-p 3000:3000 \
	-p 4317:4317 \
	-p 4318:4318 \
	--rm \
	-ti \
	-v "$PWD"/container/grafana:/data/grafana \
	-v "$PWD"/container/prometheus:/data/prometheus \
	-v "$PWD"/container/loki:/data/loki \
	-e GF_PATHS_DATA=/data/grafana \
	-e GF_INSTALL_PLUGINS="grafana-image-renderer" \
	-e GF_INSTALL_IMAGE_RENDERER_PLUGIN=true \
	-e GF_LOG_FILTERS=rendering:debug \
	--env-file .env \
	docker.io/grafana/otel-lgtm:"${RELEASE}"
```

```bash
...

docker run \
	--name lgtm \
	-p 3000:3000 \
	-p 4317:4317 \
	-p 4318:4318 \
        -p 8081:8081 \
	--rm \
	-ti \
	-v "$PWD"/container/grafana:/data/grafana \
	-v "$PWD"/container/prometheus:/data/prometheus \
	-v "$PWD"/container/loki:/data/loki \
	-e GF_PATHS_DATA=/data/grafana \
	-e GF_INSTALL_PLUGINS="grafana-image-renderer" \
	-e GF_INSTALL_IMAGE_RENDERER_PLUGIN=true \
	-e GF_RENDERING_SERVER_URL="http://localhost:8081/render" \
	-e GF_RENDERING_CALLBACK_URL="http://localhost:3000" \
	-e GF_LOG_FILTERS=rendering:debug \
	--env-file .env \
	docker.io/grafana/otel-lgtm:"${RELEASE}"
```

But can't see the `Installed` tag at http://localhost:3000/plugins/grafana-image-renderer

![image](https://github.com/user-attachments/assets/898c857a-9bc8-4660-8205-59b240574d5e)

Nor do I see the Image Renderer related logs when starting up

```
latest: Pulling from grafana/otel-lgtm
Digest: sha256:0d4e0cbb87b38112ba4b8e411f81925ab0f78cce3c5b219c327e8b06c1b67c23
Status: Image is up to date for grafana/otel-lgtm:latest
docker.io/grafana/otel-lgtm:latest
Running Grafana v11.6.0 logging=false
Running OpenTelemetry Collector v0.124.0 logging=false
Running Prometheus v3.2.1 logging=false
Running Tempo v2.7.2 logging=false
Running Loki v3.4.3 logging=false
Waiting for the OpenTelemetry collector and the Grafana LGTM stack to start up...
Running Pyroscope v1.13.1 logging=false
Prometheus is up and running. Startup time: 2 seconds
OpenTelemetry collector is up and running. Startup time: 2 seconds
Grafana is up and running. Startup time: 3 seconds
Pyroscope is up and running. Startup time: 3 seconds
Loki is up and running. Startup time: 3 seconds
Tempo is up and running. Startup time: 3 seconds
Total startup time: 3 seconds

Startup Time Summary:
---------------------
Grafana: 3 seconds
Loki: 3 seconds
Prometheus: 2 seconds
Tempo: 3 seconds
Pyroscope: 3 seconds
OpenTelemetry collector: 2 seconds
Total: 3 seconds
The OpenTelemetry collector and the Grafana LGTM stack are up and running. (created /tmp/ready)
Open ports:
 - 4317: OpenTelemetry GRPC endpoint
 - 4318: OpenTelemetry HTTP endpoint
 - 3000: Grafana. User: admin, password: admin
 ```

Not sure which step is wrong

---

https://github.com/grafana/grafana/blob/519b75bd1eecc07c48efad8dc545596b3a030834/packaging/docker/custom/Dockerfile#L5-L46

---

```bash
$ curl -s http://localhost:3000/api/plugins | jq '.[].id'
"alertlist"
"alertmanager"
"annolist"
"grafana-azure-monitor-datasource"
"barchart"
"bargauge"
"candlestick"
"canvas"
"cloudwatch"
"dashlist"
"datagrid"
"elasticsearch"
"flamegraph"
"gauge"
"geomap"
"gettingstarted"
"stackdriver"
"grafana-lokiexplore-app"
"grafana-pyroscope-app"
"grafana-pyroscope-datasource"
"graph"
"graphite"
"heatmap"
"histogram"
"yesoreyeram-infinity-datasource"
"influxdb"
"jaeger"
"logs"
"loki"
"mssql"
"mysql"
"news"
"nodeGraph"
"opentsdb"
"parca"
"piechart"
"grafana-postgresql-datasource"
"prometheus"
"stat"
"state-timeline"
"status-history"
"table"
"table-old"
"tempo"
"grafana-testdata-datasource"
"text"
"timeseries"
"traces"
"trend"
"welcome"
"xychart"
"zipkin"

$ curl -s http://localhost:3000/api/plugins/grafana-image-renderer | jq
{
  "message": "Not found"
}

$ docker exec lgtm env | grep GF_
GF_RENDERING_SERVER_URL=http://localhost:8081/render
GF_RENDERING_CALLBACK_URL=http://localhost:3000/
GF_RENDERING_RENDERER_URL=http://localhost:8081
GF_RENDERING_MODE=browser
GF_PATHS_DATA=/data/grafana
GF_INSTALL_PLUGINS=grafana-image-renderer
GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
GF_LOG_FILTERS=rendering:debug
```

**Comment by daviddwlee84** [comment, marked as answer]
This docker compose works for now

```yaml
services:
  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: lgtm
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    volumes:
      - ./container/grafana:/data/grafana
      - ./container/prometheus:/data/prometheus
      - ./container/loki:/data/loki
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://lgtm:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_PATHS_DATA=/data/grafana
    restart: unless-stopped
    networks:
      - monitoring

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - '8081:8081'
    environment:
      - ENABLE_METRICS=true
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge 
```

But might not be the best answer
