### ISSUE TITLE
Grafana Login Disabled

### ISSUE THREAD

**Issue by ondiekisteven** [grafana/docker-otel-lgtm#153]
How do I enable granana dashboard login by default. I've tried setting the environment variable GF_AUTH_ANONYMOUS_ENABLED=false but doesn't seem to disable anonymous access

**Comment by zeitlinger** [comment]
these settings are changed - and should be reverted to their original state: https://github.com/grafana/docker-otel-lgtm/blob/main/docker/run-grafana.sh#L5-L6

See https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/grafana/#anonymous-authentication

**Comment by ferkanzai** [comment]
What I did is access the container, open `run-grafana.sh`, modify de env var to `false` and the kill the grafana process and run `sh run-grafana.sh` to start grafana again. That worked for me!

**Comment by zeitlinger** [comment]
great!

**Comment by FractalMind** [comment]
```
  grafana-otel:
    image: grafana/otel-lgtm:0.8.4
    container_name: grafana-otel
    restart: always
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "haohanyang-mongodb-datasource"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/plugins:/data/grafana/plugins
      - ./grafana/run-grafana.sh:/otel-lgtm/run-grafana.sh
      - grafana_data:/data
```
