### ISSUE TITLE
feature: add promote resource attributes

### ISSUE THREAD

**Issue by arukiidou** [grafana/docker-otel-lgtm#155]
### sumamry

adding promote resource attributes

### prometheus docs

https://prometheus.io/docs/guides/opentelemetry/#promoting-resource-attributes

> The following snippet shares the best practise set of attributes to promote:

```yaml
otlp:
  # Recommended attributes to be promoted to labels.
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name
    - k8s.cluster.name
    - k8s.container.name
    - k8s.cronjob.name
    - k8s.daemonset.name
    - k8s.deployment.name
    - k8s.job.name
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.replicaset.name
    - k8s.statefulset.name
```
