### ISSUE TITLE
Loki does not show log in JSON

### ISSUE THREAD

**Issue by nguyen-tri-nhan** [grafana/docker-otel-lgtm#276]
I am using grafana/otel-lgtm:latest `c8377cd70d24` in docker-compose

My config:
```yaml
version: "3.9"
services:
  grafana:
    container_name: grafana
    image: grafana/otel-lgtm:latest
    ports:
      - "3111:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      ENABLE_LOGS_ALL: "true"
      OTEL_METRIC_EXPORT_INTERVAL: 1000
    healthcheck:
      test: test -e /tmp/ready
      interval: 5s
      timeout: 2s
      retries: 20
```

My application uses Quarkus 3.18.2, I want to export logs to Loki for my exploring purpose.
I've added `quarkus-logging-json` to the project
```kts
    implementation("io.quarkus:quarkus-logging-json")
```
My config in development profile:
```env
%dev.quarkus.log.console.json=true
%dev.quarkus.otel.logs.enabled=true
%dev.quarkus.otel.service.name=my-service
```

My log in the IntelliJ console is shown in JSON format
<img width="1457" alt="Image" src="https://github.com/user-attachments/assets/3a8ed9ed-dede-4c95-9975-10a895ba4322" />

But when I go to Loki, it still shows logs in normal configuration.
![Image](https://github.com/user-attachments/assets/b29d90d5-518c-43bd-bf74-21f2ed150b34)

Do we have any steps to config the Loki to consume and parse logs in JSON format?
