### ISSUE TITLE
metric - trace link name update for prometheus datasource of grafana

### ISSUE THREAD

**Issue by flytux** [grafana/docker-otel-lgtm#278]
Hi, I've installed otel-lgtm in k8s cluster as backend, receiving otlp metrics, logs, traces from opentelemetry java agent. (with rolldice sample, auth instrumetations)

Everything is okay except metric exemplar link to trace. 

After I revised grafana datasource of prometheus slightly (traceID to trace_id as follows), I think it works fine.

```
data:
  grafana-datasources.yaml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://localhost:9090
        jsonData:
          timeInterval: 60s
          exemplarTraceIdDestinations:
            - name: trace_id          # traceID >> trace_id
              datasourceUid: tempo
              urlDisplayLabel: "Trace: ${__value.raw}")
```
