### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by TomKeur** [grafana/docker-otel-lgtm#29]
I'm trying out the Docker image on my Macbook (with ARM CPU), and I'm seeing the following error:

> grafana-lgtm The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

I'm not seeing any traces are coming in, in Tempo, but I'm not sure if it's related (but I do not think so, since I've never had it working before :p).

Not sure it's already on the roadmap.

As a workaround I've added:

```yaml
  platform: linux/amd64
```

to my `compose.yaml` file.

**Comment by grcevski** [comment]
Thanks for reporting this! Would you be interested in contributing an ARM64 compose file? I think your workaround is the correct solution here.

**Comment by TomKeur** [comment]
The run command: https://github.com/grafana/docker-otel-lgtm/blob/main/run-lgtm.sh#L3C1-L3C77

Would be:

```bash
docker run --platform linux/amd64 -p 3000:3000 -p 4317:4317 -p 4318:4318 --rm -ti grafana/otel-lgtm
```

My docker-compose looks like this:
```yaml
services: 
  grafana-otel-lgtm:
    platform: linux/amd64
    image: grafana/otel-lgtm
    container_name: grafana-otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
```

It's part of my "default" services `docker-compose.yaml` file.
Btw, I've also managed to get data in, so thats all working :).
