### ISSUE TITLE
Provide simple Kubernetes YAML

### ISSUE THREAD

**Issue by howardjohn** [grafana/docker-otel-lgtm#36]
For Kubernetes deployments, it may be nice to provide a simple YAML. Not hard to make one manually, but harder than copy+paste :slightly_smiling_face: 

Below shows a good start.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
spec:
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
      - name: lgtm
        image: grafana/otel-lgtm
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm
spec:
  selector:
    app: lgtm
  ports:
  - name: ui
    port: 3000
  - name: grpc
    port: 4317
  - name: https
    port: 4318
```
