### ISSUE TITLE
Using otlp with prometheus and loki

### ISSUE THREAD

**Issue by arukiidou** [grafana/docker-otel-lgtm#40]
As a user, thank you for creating otel-lgtm.

If using otlp in all components, it would be more easier to migrate from other components to lgtm, from lgtm to individual (prometheus, tempo, loki).

Can I contribute to this?

```[tasklist]
### Tasks
- [x] Enable out_of_order_time_window in prometheus _#42
- [ ] #42
- [ ] #41
- [x] fix regression: #48
- [ ] #44
```

**Comment by zeitlinger** [comment]
I don't understand - can you elaborate?

**Comment by arukiidou** [comment]
this is how we want otelcol to be:

- replace prometheusremotewriteexporter to otlpexporter
- replace lokiexporter to otlpexporter

```yaml
exporters:
  otlp/traces:
    endpoint: http://localhost:4418
  otlp/metrics:
    endpoint: http://localhost:9090/api/v1/otlp/
  otlp/logs:
    endpoint: http://localhost:3100/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
    metrics:
      receivers: [otlp,prometheus/collector]
      processors: [batch]
      exporters: [otlp/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/logs]
```
