### ISSUE TITLE
OTEL_EXPORTER_OTLP_ENDPOINT is not working as expected.

### ISSUE THREAD

**Issue by vardanaloyan** [grafana/docker-otel-lgtm#447]
As mentioned in the Documentation if we would like additionally export traces into other back-end platforms we could use OTEL_EXPORTER_OTLP_ENDPOINT environment variable.

https://github.com/grafana/docker-otel-lgtm?tab=readme-ov-file#send-data-to-vendors

```
Send data to vendors

In addition to the built-in observability tools, you can also send data to vendors. That way, you can easily try and switch between different backends.

If the [OTEL_EXPORTER_OTLP_ENDPOINT](https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_endpoint) variable is set, the OpenTelemetry Collector will send data (logs, metrics, and traces) to the specified endpoint using "OTLP/HTTP".
```

My current local development setup is the following:
I have docker-compose running application, jaeger and grafana (otel-lgtm).
They share the same network.
I can see application metrics in Grafana, and I want additionally send traces to a Jaeger.
Here's the part of Docker compose including otel-lgtm and jaeger

```
services:
  application:
    ...
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    ports:
      - 16686:16686
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      test:
        aliases: 
          - jaeger

  grafana:
    image: grafana/otel-lgtm
    restart: unless-stopped
    user: '0'
    ports:
      - 3000:3000
    environment:
      OTEL_METRIC_EXPORT_INTERVAL: 500
      ENABLE_LOGS_OTELCOL: true
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
    volumes:
      - './misc/data:/var/lib/grafana'
    networks:
      test:
        aliases: 
          - otel-lgtm
networks:
  test:
    driver: bridge
```

After running the application and triggering some calls I receive metrics in Grafana Dashboard, but I see following error in the logs and I don't have any data in Jaeger.

```
2025-04-29T14:20:09.203Z info internal/retry_sender.go:133 Exporting failed. Will retry the request after interval. {"error": "failed to make an HTTP request: Post \"jaeger:4317/v1/metrics\": unsupported protocol scheme \"jaeger\"", "interval": "21.177012267s"}
```

I think it is a bug, because even though I specified gRPC endpoint it still tries to make an HTTP call.
