### ISSUE TITLE
Change Grafana UI Port 3000?

### ISSUE THREAD

**Issue by melloware** [grafana/docker-otel-lgtm#461]
My Docker Compose

```yml
 otel-lgtm:
    image: docker.io/grafana/otel-lgtm
    ports:
      - "3000:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=test
    volumes:
      - otel-lgtm-data:/var/lib/grafana
```

If I try and remap `- "3001:3000"` because i want it on 3001 instead of 3000 to not break my other JavaScript Vite apps that use 3000 then you can't reach Grafana at 3001.  It does not work and responds with no data.
