### ISSUE TITLE
Remove grafana version from directory name

### ISSUE THREAD

**Issue by jaydeluca** [grafana/docker-otel-lgtm#61]
First of all, thank you for creating this image. It is simplifying a workflow I use all the time to prototype or quickly spin up telemetry examples.

I was curious if the version number being included in the grafana directory name is strict requirement? The reason I ask is because I will sometimes create a custom dashboard and want to mount it within the container automatically, but currently this requires me to know the exact version of grafana running within the container:

```
version: '3'
services:
  collector:
    image: grafana/otel-lgtm:latest
    ports:
      - "4317:4317"
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/otel-lgtm/dashboards
      - ./grafana/dashboards.yaml:/otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/dashboards.yaml
```

It would be much simpler to maintain if grafana was installed into a generic `grafana` directory where I could more simply just do:

```
    volumes:
      - ./grafana/dashboards:/otel-lgtm/dashboards
      - ./grafana/dashboards.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/dashboards.yaml
```
