### ISSUE TITLE
Set explicit TLSconfig

### ISSUE THREAD

**Issue by arukiidou** [grafana/docker-otel-lgtm#68]
Follow the official example, Set explicit TLSconfig
https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/configtls#client-configuration

### example

```yaml
  otlp/insecure:
    endpoint: myserver.local:55690
    tls:
      insecure: true
```
