### ISSUE TITLE
Enable Tempo spanmetrics

### ISSUE THREAD

**Issue by Starefossen** [grafana/docker-otel-lgtm#83]
Tempo spanmetrics seams to not be enabled, would you accept a PR for that?

**Comment by zeitlinger** [comment]
sure :smile:

**Comment by lucax88x** [comment]
if someones stumbles on how to configure that:

1) download their tempo-config in a local dir

2) bind your local tempo-confg.yaml to their container:

    volumes:
      - ${PWD}/docker/otel-lgtm/tempo-config.yaml:/otel-lgtm/tempo-config.yaml
 
3) configure tempo config, for example with:

```yaml
overrides:
  metrics_generator_processors: [service-graphs, local-blocks, span-metrics]
  max_bytes_per_trace: x
```

use this [link](https://github.com/grafana/tempo/blob/fbf249a41fdc9ee9ddc8168c4a4f92e426f92bb0/modules/overrides/config_legacy.go#L73)

to understand which key you can use, we have to use legacy config and you cannot refer to grafana docs sadly.
